### PR TITLE
Replace Result returns in API with callback based error handling

### LINKED ISSUE #38: Resolve Operator Overloading Disparity
Keeping this one here till either:
  1. Rust provides a better interface / error handling for this (or)
  2. We strip the overloading and resort to af::add () , etc.

In this case 1 > 2

### LINKED ISSUE #45: Better Arrayfire Expressions Syntax
I am thinking of a better way of expressing arrayfire expressions in rust, however still needs some work on the design.

We can create macros describing an arrayfire expressions, like this:
```rust
let dims = af::Dim4::new(&[10, 10, 1, 1]);
let a = af::randu(dims, Aftype::F32)
let result = af::expression!(
    |expr, err| println!("'{}' Calculation failure, error: {}", expr, err),
    af::sin(1) / a + a);

let result = af::retry!(
    3,
    |expr, err| println!("'{}' Calcuation failure, error: {}", expr, err),
    af::retry_expression!(af::sin(1) / a + a));
```

Most of the time I'm quite bored with a lot of `and_then` appearing in my arrayfire-rust code, and creating a lot of disambiguation in expresstions.

However, the with the error appearing, generally people will:
1. print the error, save the state and calculated results and let it panic. Then, let other daemon scripts restart the program.
2. retry the calculation

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #45 
Fixes #38 

With this change, all functions and operations return appropriate
values/objects instead of wrapping those values inside a Result<>
object. All errors reported by FFI calls are handled by a global
error handling function that is registered by a call to the function
`register_error_handler` that accepts either a closure or a function.

By default, the error handler is set to a internal function that
prints the error message to standard output and then panics.

### CODE REVIEW

**Comment by 9prady9** [comment]
@arrayfire/rust-devel 

Feedback please.

File: src/error.rs [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+pub fn register_error_handler(callback: &'static ErrorCallback) {
+    unsafe {
+        HANDLE_ERROR = callback;
+    }
+}
+
+pub fn handle_error_general(error_code: AfError) {
+    match error_code {
+        AfError::SUCCESS            => {}, /* No-op */
```
Comment (jramapuram) [inline src/error.rs]: Suggestion: use the function (maybe move it outside of the trait impl) to get the `&str` 's here to avoid having code dupes:
```rust
impl Error for AfError {
    fn description(&self) -> &str {
```

**Comment by jramapuram** [comment]
@9prady9 : Looks good besides the comment above!

File: src/error.rs (hunk 1 above)
Comment (9prady9) [inline src/error.rs]: Good idea, will look into it.

@jramapuram Was wondering if global static HANDLE_ERROR should be mutex protected apart from being inside unsafe block ? Any idea about that ?

Comment (jramapuram) [inline src/error.rs]: First question: why does it need to be unsafe? Its just a standard rust panic function.

Don't see a need for mutexing. There is no shared data in these handlers. They are independent.

Comment (9prady9) [inline src/error.rs]: Enclosing the code that mutates mutable static global inside an unsafe block is mandatory. Check [here](https://doc.rust-lang.org/book/const-and-static.html#mutability).

Comment (jramapuram) [inline src/error.rs]: Ah ok, that makes sense. In this case it would only need a mutex if you think people would be modifying the handler (at runtime) from multiple threads. If that is the case then yes it should be mutexed.

Comment (jramapuram) [inline src/error.rs]: Also you would need this: https://doc.rust-lang.org/std/sync/struct.StaticMutex.html as static does not implement `Drop`

Comment (9prady9) [inline src/error.rs]: Yes, that is scenario i had in mind when asked about it. Well, I am not sure if modifying the handler mid program is practical. Usually, whatever error handling code is written doesn't change during program execution.

Comment (9prady9) [inline src/error.rs]: Yes, we would need a static mutex if we need one at all.

Comment (jramapuram) [inline src/error.rs]: True, but it is conceivable that the user wants a different method of error handling at a different point in the program execution and we should be robust in upholding that

Comment (9prady9) [inline src/error.rs]: True, agree with that.

Comment (9prady9) [inline src/error.rs]: Regarding Error trait, i didn't notice. I have already implemented in `defines` module. Just need to reuse it.

Comment (jramapuram) [inline src/error.rs]: Yup, what I suggested ;p

**Comment by 9prady9** [comment]
@jramapuram StaticMutex is unstable and can't be used unless in Non-stable channels. I am not sure how else we can do it as of now. Other than that, i think i finished other changes.

**Comment by jramapuram** [comment]
How about using lazy static:

```rust
#[macro_use]
extern crate lazy_static;

use std::sync::Mutex;

lazy_static! {
    static ref ARRAY: Mutex<Vec<u8>> = Mutex::new(vec![]);
}

fn do_a_call() {
    ARRAY.lock().unwrap().push(1);
}

fn main() {
    do_a_call();
    do_a_call();
    do_a_call();

    println!("called {}", ARRAY.lock().unwrap().len());
}
```
(http://stackoverflow.com/questions/27791532/how-do-i-create-a-global-mutable-singleton)

**Comment by 9prady9** [comment]
@jramapuram Check out the latest commit and let me know what you think.

File: src/error.rs [hunk 2]
```diff
@@ -1,11 +1,19 @@
+
 use defines::AfError;
 use std::error::Error;
+use std::sync::Mutex;
 
 pub type ErrorCallback = Fn(AfError);
 
 pub static mut HANDLE_ERROR: &'static ErrorCallback = &handle_error_general;
```
Comment (jramapuram) [inline src/error.rs]: @9prady9 : I don't think this does what you are expecting.
I would assume this would look like [havent tested] :
```rust
lazy_static! {
    static ref ARRAY: Mutex<ErrorCallback> = Mutex::new(&handle_error_general);
}
```

Then every call would be  `HANDLE_ERROR.lock().unwrap()(af_err)`

This would ensure that when you swap out the `HANDLE_ERROR` function from a thread it would then lock the currently stored function (and thus ensure that the currently registered one would be called).

Comment (9prady9) [inline src/error.rs]: I have tried passing ErrorCallback to Mutex, but that didn't compile for me. Therefore, i created the mutex around an integer.

Yes, i see it now, this is wrong. Won't help protect the data.

Comment (jramapuram) [inline src/error.rs]: Can you try a reference to a function (instead of a function) or even a Box maybe?

Comment (9prady9) [inline src/error.rs]: I think i tried reference, but that doesn't work because it will require life time specifier. Adding 'static life time brings us back to the old problem of not being able to create a Mutex around 'static life time object.

I don't remember trying Box but i suspect it will have similar problem. But will give it a shot.

Comment (9prady9) [inline src/error.rs]: Hm, i think i found the root cause of this. `Fn(AfError)` needs to have Send and Sync traits implemented for it to be used either in the context of `Box` or `static mut`.

I am getting the error explained in the output of `rustc --explain E0117` if try to impl implement Send/Sync.

File: src/arith/mod.rs [hunk 3]
```diff
@@ -336,4 +341,49 @@ arith_func!(BitAnd, bitand, af_bitand);
...
+    ($op_name:ident, $fn_name:ident, $func: ident) => (
+        impl $op_name<Array> for Array {
+
+            #[allow(unused_variables)]
+            fn $fn_name(&mut self, rhs: Array) {
+                let mut idxrs = Indexer::new();
+                idxrs.set_index(&Seq::<f32>::default(), 0, Some(false));
+                idxrs.set_index(&Seq::<f32>::default(), 1, Some(false));
+                let tmp = assign_gen(self as &Array, &idxrs, & $func(self as &Array, &rhs));
+                mem::replace(self, tmp);
```
Comment (9prady9) [inline src/arith/mod.rs]: @jramapuram Any idea if i am creating any leaks here ?

Comment (jramapuram) [inline src/arith/mod.rs]: @9prady9 : sorry for the delay. According to the docs `mem::replace` does **not** deinitialize the old value. It does however return the previous value. I think de-initializing manually here is the apt choice to prevent a dangling pointer. I'm not too worried about the actual array since that is a smart pointer in C++. Thoughts @pavanky ?

**Comment by jramapuram** [comment]
@9prady9 : So you can't implement `Sync + Send` for the lambda?

**Comment by 9prady9** [comment]
@jramapuram Nope, doesn't seem like it. I tried doing something similar to the following

```rust
struct MyBox(*mut u8);

unsafe impl Send for MyBox {}
unsafe impl Sync for MyBox {}
```

for `ErrorCallback` type but the rust compiler keeps throwing out the following message

```rust
src\error.rs:24:1: 24:38 error: the impl does not reference any types defined in this crate; only traits defined in the current crate can be implemented for arbitrary types [E0117]
src\error.rs:24 unsafe impl Send for ErrorCallback {}
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src\error.rs:24:1: 24:38 help: run `rustc --explain E0117` to see a detailed explanation

```

**Comment by 9prady9** [comment]
Putting the function pointer inside a struct compiled the code, but have to test this if it is doing what we need to do.

```
struct MyCB(*mut ErrorCallback);

unsafe impl Send for MyCB {}
```

**Comment by 9prady9** [comment]
@jramapuram I came up with something like [this](https://gist.github.com/9prady9/1b0e23b529a38ffb01468f45149678cd) and modified the test to look like [this ](https://gist.github.com/9prady9/4a569dcb6c8f0e6f9097ff4bce620db3)and trying to debug any issues with this.

Also, i will probably replace `Mutex` with `RwLock` if i can which seems more appropriate.

**Comment by 9prady9** [comment]
@arrayfire/rust-devel Please take a look at the latest changes for error handler thread safety and let me know if there are any issues.

Thanks.

File: tests/lib.rs [hunk 4]
```diff
@@ -1,42 +1,58 @@
...
+                1 => register_error_handler(HANDLE2.clone()),
+                2 => register_error_handler(HANDLE3.clone()),
+                3 => register_error_handler(HANDLE4.clone()),
+                _ => panic!("Impossible scenario"),
             }
+            //match i {
+            //    1 => thread::sleep(Duration::from_millis(20)),
+            //    2 => thread::sleep(Duration::from_millis(10)),
+            //    _ => (),
+            //}
```
Comment (jramapuram) [inline tests/lib.rs]: unnecessary comments?

File: src/error.rs [hunk 5]
```diff
@@ -1,15 +1,44 @@
...
+unsafe impl<'cblifetime> Send for Callback<'cblifetime> {}
+unsafe impl<'cblifetime> Sync for Callback<'cblifetime> {}
+
+
+pub static DEFAULT_HANDLE_ERROR: &'static ErrorCallback = &handle_error_general;
+
+
+lazy_static! {
+    static ref ERROR_HANDLER_LOCK: RwLock< Callback<'static> > =
+        RwLock::new(Callback{cb: DEFAULT_HANDLE_ERROR});
```
Comment (jramapuram) [inline src/error.rs]: I like the `RwLock` solution, good work @9prady9  :)

**Comment by jramapuram** [comment]
Looks good @9prady9 !

File: tests/lib.rs (hunk 4 above)
Comment (9prady9) [inline tests/lib.rs]: My bad, will remove them, i must have forgotten them after some debugging.
